Warning: Permanently added '[nid00777]:6999,[10.128.3.16]:6999' (RSA) to the list of known hosts.
Traceback (most recent call last):
  File "/home1/03284/bjack/.local/bin/pinetree_run.py", line 6, in <module>
    exec(compile(open(__file__).read(), __file__, 'exec'))
  File "/work/03284/bjack/lonestar/pinetree/bin/pinetree_run.py", line 47, in <module>
    main()
  File "/work/03284/bjack/lonestar/pinetree/bin/pinetree_run.py", line 42, in main
    run(my_params_file, outfile, args.seed)
  File "/work/03284/bjack/lonestar/pinetree/bin/pinetree_run.py", line 11, in run
    with open(params_file, "r") as my_file:
FileNotFoundError: [Errno 2] No such file or directory: './T7_012318_wt.yml'
Traceback (most recent call last):
  File "/home1/03284/bjack/.local/bin/pinetree_run.py", line 6, in <module>
    exec(compile(open(__file__).read(), __file__, 'exec'))
  File "/work/03284/bjack/lonestar/pinetree/bin/pinetree_run.py", line 47, in <module>
    main()
  File "/work/03284/bjack/lonestar/pinetree/bin/pinetree_run.py", line 42, in main
    run(my_params_file, outfile, args.seed)
  File "/work/03284/bjack/lonestar/pinetree/bin/pinetree_run.py", line 11, in run
    with open(params_file, "r") as my_file:
FileNotFoundError: [Errno 2] No such file or directory: './T7_012318b_wt.yml'
